/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:436987:
  appc.background(230);
} //_CODE_:window1:436987:

public void questionChange(GTextArea source, GEvent event) { //_CODE_:questionText:652546:

} //_CODE_:questionText:652546:

public void answerChange(GTextArea source, GEvent event) { //_CODE_:answerText:963032:

} //_CODE_:answerText:963032:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:778303:
  println(questionText.getText(), answerText.getText());
  questionText.setText("");
  answerText.setText("");
  
} //_CODE_:button1:778303:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 600, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  questionText = new GTextArea(window1, 10, 30, 290, 80, G4P.SCROLLBARS_NONE);
  questionText.setOpaque(true);
  questionText.addEventHandler(this, "questionChange");
  answerText = new GTextArea(window1, 10, 140, 290, 80, G4P.SCROLLBARS_NONE);
  answerText.setOpaque(true);
  answerText.addEventHandler(this, "answerChange");
  label1 = new GLabel(window1, 110, 10, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Question");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 110, 120, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Answer");
  label2.setOpaque(false);
  button1 = new GButton(window1, 110, 240, 80, 30);
  button1.setText("Submit");
  button1.addEventHandler(this, "button1_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GTextArea questionText; 
GTextArea answerText; 
GLabel label1; 
GLabel label2; 
GButton button1; 
